// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterMonitoring.proto

package ds.waterMonitoring;

/**
 * Protobuf type {@code waterMonitoring.MonitorAreaResponse}
 */
public  final class MonitorAreaResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:waterMonitoring.MonitorAreaResponse)
    MonitorAreaResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MonitorAreaResponse.newBuilder() to construct.
  private MonitorAreaResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MonitorAreaResponse() {
    waterUsage_ = 0;
    issues_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MonitorAreaResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            waterUsage_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            issues_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_MonitorAreaResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_MonitorAreaResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.waterMonitoring.MonitorAreaResponse.class, ds.waterMonitoring.MonitorAreaResponse.Builder.class);
  }

  public static final int WATERUSAGE_FIELD_NUMBER = 1;
  private int waterUsage_;
  /**
   * <code>int32 waterUsage = 1;</code>
   */
  public int getWaterUsage() {
    return waterUsage_;
  }

  public static final int ISSUES_FIELD_NUMBER = 2;
  private volatile java.lang.Object issues_;
  /**
   * <code>string issues = 2;</code>
   */
  public java.lang.String getIssues() {
    java.lang.Object ref = issues_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      issues_ = s;
      return s;
    }
  }
  /**
   * <code>string issues = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIssuesBytes() {
    java.lang.Object ref = issues_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      issues_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (waterUsage_ != 0) {
      output.writeInt32(1, waterUsage_);
    }
    if (!getIssuesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, issues_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (waterUsage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, waterUsage_);
    }
    if (!getIssuesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, issues_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.waterMonitoring.MonitorAreaResponse)) {
      return super.equals(obj);
    }
    ds.waterMonitoring.MonitorAreaResponse other = (ds.waterMonitoring.MonitorAreaResponse) obj;

    boolean result = true;
    result = result && (getWaterUsage()
        == other.getWaterUsage());
    result = result && getIssues()
        .equals(other.getIssues());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WATERUSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getWaterUsage();
    hash = (37 * hash) + ISSUES_FIELD_NUMBER;
    hash = (53 * hash) + getIssues().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.waterMonitoring.MonitorAreaResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.waterMonitoring.MonitorAreaResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code waterMonitoring.MonitorAreaResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:waterMonitoring.MonitorAreaResponse)
      ds.waterMonitoring.MonitorAreaResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_MonitorAreaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_MonitorAreaResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.waterMonitoring.MonitorAreaResponse.class, ds.waterMonitoring.MonitorAreaResponse.Builder.class);
    }

    // Construct using ds.waterMonitoring.MonitorAreaResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      waterUsage_ = 0;

      issues_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_MonitorAreaResponse_descriptor;
    }

    @java.lang.Override
    public ds.waterMonitoring.MonitorAreaResponse getDefaultInstanceForType() {
      return ds.waterMonitoring.MonitorAreaResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.waterMonitoring.MonitorAreaResponse build() {
      ds.waterMonitoring.MonitorAreaResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.waterMonitoring.MonitorAreaResponse buildPartial() {
      ds.waterMonitoring.MonitorAreaResponse result = new ds.waterMonitoring.MonitorAreaResponse(this);
      result.waterUsage_ = waterUsage_;
      result.issues_ = issues_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.waterMonitoring.MonitorAreaResponse) {
        return mergeFrom((ds.waterMonitoring.MonitorAreaResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.waterMonitoring.MonitorAreaResponse other) {
      if (other == ds.waterMonitoring.MonitorAreaResponse.getDefaultInstance()) return this;
      if (other.getWaterUsage() != 0) {
        setWaterUsage(other.getWaterUsage());
      }
      if (!other.getIssues().isEmpty()) {
        issues_ = other.issues_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.waterMonitoring.MonitorAreaResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.waterMonitoring.MonitorAreaResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int waterUsage_ ;
    /**
     * <code>int32 waterUsage = 1;</code>
     */
    public int getWaterUsage() {
      return waterUsage_;
    }
    /**
     * <code>int32 waterUsage = 1;</code>
     */
    public Builder setWaterUsage(int value) {
      
      waterUsage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 waterUsage = 1;</code>
     */
    public Builder clearWaterUsage() {
      
      waterUsage_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object issues_ = "";
    /**
     * <code>string issues = 2;</code>
     */
    public java.lang.String getIssues() {
      java.lang.Object ref = issues_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        issues_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string issues = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIssuesBytes() {
      java.lang.Object ref = issues_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        issues_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string issues = 2;</code>
     */
    public Builder setIssues(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      issues_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string issues = 2;</code>
     */
    public Builder clearIssues() {
      
      issues_ = getDefaultInstance().getIssues();
      onChanged();
      return this;
    }
    /**
     * <code>string issues = 2;</code>
     */
    public Builder setIssuesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      issues_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:waterMonitoring.MonitorAreaResponse)
  }

  // @@protoc_insertion_point(class_scope:waterMonitoring.MonitorAreaResponse)
  private static final ds.waterMonitoring.MonitorAreaResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.waterMonitoring.MonitorAreaResponse();
  }

  public static ds.waterMonitoring.MonitorAreaResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MonitorAreaResponse>
      PARSER = new com.google.protobuf.AbstractParser<MonitorAreaResponse>() {
    @java.lang.Override
    public MonitorAreaResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MonitorAreaResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MonitorAreaResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MonitorAreaResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.waterMonitoring.MonitorAreaResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

