// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterMonitoring.proto

package ds.waterMonitoring;

public interface MonitorAreaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterMonitoring.MonitorAreaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 waterUsage = 1;</code>
   */
  int getWaterUsage();

  /**
   * <code>string issues = 2;</code>
   */
  java.lang.String getIssues();
  /**
   * <code>string issues = 2;</code>
   */
  com.google.protobuf.ByteString
      getIssuesBytes();
}
