// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterMonitoring.proto

package ds.waterMonitoring;

public interface SendSensorDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterMonitoring.SendSensorDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string areaName = 1;</code>
   */
  java.lang.String getAreaName();
  /**
   * <code>string areaName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaNameBytes();

  /**
   * <code>int32 waterUsage = 2;</code>
   */
  int getWaterUsage();

  /**
   * <code>string waterLeak = 3;</code>
   */
  java.lang.String getWaterLeak();
  /**
   * <code>string waterLeak = 3;</code>
   */
  com.google.protobuf.ByteString
      getWaterLeakBytes();
}
