// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterMonitoring.proto

package ds.waterMonitoring;

public interface SendSensorDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterMonitoring.SendSensorDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alert = 1;</code>
   */
  java.lang.String getAlert();
  /**
   * <code>string alert = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlertBytes();

  /**
   * <code>string recommendation = 2;</code>
   */
  java.lang.String getRecommendation();
  /**
   * <code>string recommendation = 2;</code>
   */
  com.google.protobuf.ByteString
      getRecommendationBytes();
}
