// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterMonitoring.proto

package ds.waterMonitoring;

/**
 * Protobuf type {@code waterMonitoring.SendSensorDataRequest}
 */
public  final class SendSensorDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:waterMonitoring.SendSensorDataRequest)
    SendSensorDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SendSensorDataRequest.newBuilder() to construct.
  private SendSensorDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendSensorDataRequest() {
    areaName_ = "";
    waterUsage_ = 0;
    waterLeak_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SendSensorDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            areaName_ = s;
            break;
          }
          case 16: {

            waterUsage_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            waterLeak_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_SendSensorDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_SendSensorDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.waterMonitoring.SendSensorDataRequest.class, ds.waterMonitoring.SendSensorDataRequest.Builder.class);
  }

  public static final int AREANAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object areaName_;
  /**
   * <code>string areaName = 1;</code>
   */
  public java.lang.String getAreaName() {
    java.lang.Object ref = areaName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      areaName_ = s;
      return s;
    }
  }
  /**
   * <code>string areaName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAreaNameBytes() {
    java.lang.Object ref = areaName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      areaName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WATERUSAGE_FIELD_NUMBER = 2;
  private int waterUsage_;
  /**
   * <code>int32 waterUsage = 2;</code>
   */
  public int getWaterUsage() {
    return waterUsage_;
  }

  public static final int WATERLEAK_FIELD_NUMBER = 3;
  private volatile java.lang.Object waterLeak_;
  /**
   * <code>string waterLeak = 3;</code>
   */
  public java.lang.String getWaterLeak() {
    java.lang.Object ref = waterLeak_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      waterLeak_ = s;
      return s;
    }
  }
  /**
   * <code>string waterLeak = 3;</code>
   */
  public com.google.protobuf.ByteString
      getWaterLeakBytes() {
    java.lang.Object ref = waterLeak_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      waterLeak_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAreaNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, areaName_);
    }
    if (waterUsage_ != 0) {
      output.writeInt32(2, waterUsage_);
    }
    if (!getWaterLeakBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, waterLeak_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAreaNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, areaName_);
    }
    if (waterUsage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, waterUsage_);
    }
    if (!getWaterLeakBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, waterLeak_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.waterMonitoring.SendSensorDataRequest)) {
      return super.equals(obj);
    }
    ds.waterMonitoring.SendSensorDataRequest other = (ds.waterMonitoring.SendSensorDataRequest) obj;

    boolean result = true;
    result = result && getAreaName()
        .equals(other.getAreaName());
    result = result && (getWaterUsage()
        == other.getWaterUsage());
    result = result && getWaterLeak()
        .equals(other.getWaterLeak());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AREANAME_FIELD_NUMBER;
    hash = (53 * hash) + getAreaName().hashCode();
    hash = (37 * hash) + WATERUSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getWaterUsage();
    hash = (37 * hash) + WATERLEAK_FIELD_NUMBER;
    hash = (53 * hash) + getWaterLeak().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.waterMonitoring.SendSensorDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.waterMonitoring.SendSensorDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code waterMonitoring.SendSensorDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:waterMonitoring.SendSensorDataRequest)
      ds.waterMonitoring.SendSensorDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_SendSensorDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_SendSensorDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.waterMonitoring.SendSensorDataRequest.class, ds.waterMonitoring.SendSensorDataRequest.Builder.class);
    }

    // Construct using ds.waterMonitoring.SendSensorDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      areaName_ = "";

      waterUsage_ = 0;

      waterLeak_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.waterMonitoring.WaterMonitoringImpl.internal_static_waterMonitoring_SendSensorDataRequest_descriptor;
    }

    @java.lang.Override
    public ds.waterMonitoring.SendSensorDataRequest getDefaultInstanceForType() {
      return ds.waterMonitoring.SendSensorDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.waterMonitoring.SendSensorDataRequest build() {
      ds.waterMonitoring.SendSensorDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.waterMonitoring.SendSensorDataRequest buildPartial() {
      ds.waterMonitoring.SendSensorDataRequest result = new ds.waterMonitoring.SendSensorDataRequest(this);
      result.areaName_ = areaName_;
      result.waterUsage_ = waterUsage_;
      result.waterLeak_ = waterLeak_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.waterMonitoring.SendSensorDataRequest) {
        return mergeFrom((ds.waterMonitoring.SendSensorDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.waterMonitoring.SendSensorDataRequest other) {
      if (other == ds.waterMonitoring.SendSensorDataRequest.getDefaultInstance()) return this;
      if (!other.getAreaName().isEmpty()) {
        areaName_ = other.areaName_;
        onChanged();
      }
      if (other.getWaterUsage() != 0) {
        setWaterUsage(other.getWaterUsage());
      }
      if (!other.getWaterLeak().isEmpty()) {
        waterLeak_ = other.waterLeak_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.waterMonitoring.SendSensorDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.waterMonitoring.SendSensorDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object areaName_ = "";
    /**
     * <code>string areaName = 1;</code>
     */
    public java.lang.String getAreaName() {
      java.lang.Object ref = areaName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string areaName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAreaNameBytes() {
      java.lang.Object ref = areaName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string areaName = 1;</code>
     */
    public Builder setAreaName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      areaName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string areaName = 1;</code>
     */
    public Builder clearAreaName() {
      
      areaName_ = getDefaultInstance().getAreaName();
      onChanged();
      return this;
    }
    /**
     * <code>string areaName = 1;</code>
     */
    public Builder setAreaNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      areaName_ = value;
      onChanged();
      return this;
    }

    private int waterUsage_ ;
    /**
     * <code>int32 waterUsage = 2;</code>
     */
    public int getWaterUsage() {
      return waterUsage_;
    }
    /**
     * <code>int32 waterUsage = 2;</code>
     */
    public Builder setWaterUsage(int value) {
      
      waterUsage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 waterUsage = 2;</code>
     */
    public Builder clearWaterUsage() {
      
      waterUsage_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object waterLeak_ = "";
    /**
     * <code>string waterLeak = 3;</code>
     */
    public java.lang.String getWaterLeak() {
      java.lang.Object ref = waterLeak_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        waterLeak_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string waterLeak = 3;</code>
     */
    public com.google.protobuf.ByteString
        getWaterLeakBytes() {
      java.lang.Object ref = waterLeak_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        waterLeak_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string waterLeak = 3;</code>
     */
    public Builder setWaterLeak(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      waterLeak_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string waterLeak = 3;</code>
     */
    public Builder clearWaterLeak() {
      
      waterLeak_ = getDefaultInstance().getWaterLeak();
      onChanged();
      return this;
    }
    /**
     * <code>string waterLeak = 3;</code>
     */
    public Builder setWaterLeakBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      waterLeak_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:waterMonitoring.SendSensorDataRequest)
  }

  // @@protoc_insertion_point(class_scope:waterMonitoring.SendSensorDataRequest)
  private static final ds.waterMonitoring.SendSensorDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.waterMonitoring.SendSensorDataRequest();
  }

  public static ds.waterMonitoring.SendSensorDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendSensorDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<SendSensorDataRequest>() {
    @java.lang.Override
    public SendSensorDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SendSensorDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SendSensorDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendSensorDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.waterMonitoring.SendSensorDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

