// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterMonitoring.proto

package ds.waterMonitoring;

public final class WaterMonitoringImpl {
  private WaterMonitoringImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterMonitoring_MonitorAreaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterMonitoring_MonitorAreaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterMonitoring_MonitorAreaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterMonitoring_MonitorAreaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterMonitoring_SendSensorDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterMonitoring_SendSensorDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterMonitoring_SendSensorDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterMonitoring_SendSensorDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025waterMonitoring.proto\022\017waterMonitoring" +
      "\"&\n\022MonitorAreaRequest\022\020\n\010areaName\030\001 \001(\t" +
      "\"9\n\023MonitorAreaResponse\022\022\n\nwaterUsage\030\001 " +
      "\001(\005\022\016\n\006issues\030\002 \001(\t\"P\n\025SendSensorDataReq" +
      "uest\022\020\n\010areaName\030\001 \001(\t\022\022\n\nwaterUsage\030\002 \001" +
      "(\005\022\021\n\twaterLeak\030\003 \001(\t\"?\n\026SendSensorDataR" +
      "esponse\022\r\n\005alert\030\001 \001(\t\022\026\n\016recommendation" +
      "\030\002 \001(\t2\330\001\n\017WaterMonitoring\022\\\n\013MonitorAre" +
      "a\022#.waterMonitoring.MonitorAreaRequest\032$" +
      ".waterMonitoring.MonitorAreaResponse\"\0000\001" +
      "\022g\n\016SendSensorData\022&.waterMonitoring.Sen" +
      "dSensorDataRequest\032\'.waterMonitoring.Sen" +
      "dSensorDataResponse\"\000(\0010\001B+\n\022ds.waterMon" +
      "itoringB\023WaterMonitoringImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_waterMonitoring_MonitorAreaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_waterMonitoring_MonitorAreaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterMonitoring_MonitorAreaRequest_descriptor,
        new java.lang.String[] { "AreaName", });
    internal_static_waterMonitoring_MonitorAreaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_waterMonitoring_MonitorAreaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterMonitoring_MonitorAreaResponse_descriptor,
        new java.lang.String[] { "WaterUsage", "Issues", });
    internal_static_waterMonitoring_SendSensorDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_waterMonitoring_SendSensorDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterMonitoring_SendSensorDataRequest_descriptor,
        new java.lang.String[] { "AreaName", "WaterUsage", "WaterLeak", });
    internal_static_waterMonitoring_SendSensorDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_waterMonitoring_SendSensorDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterMonitoring_SendSensorDataResponse_descriptor,
        new java.lang.String[] { "Alert", "Recommendation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
