// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterRecycling.proto

package ds.waterRecycling;

public interface MonitorTankLevelsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterRecycling.MonitorTankLevelsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tankId = 1;</code>
   */
  int getTankId();
}
