// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterRecycling.proto

package ds.waterRecycling;

public interface RainwaterTankResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterRecycling.RainwaterTankResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tankLevels = 1;</code>
   */
  int getTankLevels();

  /**
   * <code>int32 currentTankUsed = 2;</code>
   */
  int getCurrentTankUsed();
}
