// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterRecycling.proto

package ds.waterRecycling;

public interface TankResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterRecycling.TankResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tankLevel = 1;</code>
   */
  int getTankLevel();
}
