// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterRecycling.proto

package ds.waterRecycling;

public final class WaterRecyclingImpl {
  private WaterRecyclingImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_TankRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_TankRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_TankResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_TankResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_MonitorTankLevelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_MonitorTankLevelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_MonitorTankLevelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_MonitorTankLevelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_RainwaterTankRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_RainwaterTankRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_RainwaterTankResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_RainwaterTankResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024waterRecycling.proto\022\016waterRecycling\"\035" +
      "\n\013TankRequest\022\016\n\006tankId\030\001 \001(\005\"!\n\014TankRes" +
      "ponse\022\021\n\ttankLevel\030\001 \001(\005\"*\n\030MonitorTankL" +
      "evelsRequest\022\016\n\006tankId\030\001 \001(\005\"A\n\031MonitorT" +
      "ankLevelsResponse\022\016\n\006tankId\030\001 \001(\005\022\024\n\014cur" +
      "rentLevel\030\002 \001(\005\"&\n\024RainwaterTankRequest\022" +
      "\016\n\006tankId\030\001 \001(\005\"D\n\025RainwaterTankResponse" +
      "\022\022\n\ntankLevels\030\001 \001(\005\022\027\n\017currentTankUsed\030" +
      "\002 \001(\0052\267\002\n\016WaterRecycling\022M\n\016CheckTankLev" +
      "el\022\033.waterRecycling.TankRequest\032\034.waterR" +
      "ecycling.TankResponse\"\000\022l\n\021MonitorTankLe" +
      "vels\022(.waterRecycling.MonitorTankLevelsR" +
      "equest\032).waterRecycling.MonitorTankLevel" +
      "sResponse\"\0000\001\022h\n\025SwitchToRainwaterTank\022$" +
      ".waterRecycling.RainwaterTankRequest\032%.w" +
      "aterRecycling.RainwaterTankResponse\"\000(\001B" +
      ")\n\021ds.waterRecyclingB\022WaterRecyclingImpl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_waterRecycling_TankRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_waterRecycling_TankRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_TankRequest_descriptor,
        new java.lang.String[] { "TankId", });
    internal_static_waterRecycling_TankResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_waterRecycling_TankResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_TankResponse_descriptor,
        new java.lang.String[] { "TankLevel", });
    internal_static_waterRecycling_MonitorTankLevelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_waterRecycling_MonitorTankLevelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_MonitorTankLevelsRequest_descriptor,
        new java.lang.String[] { "TankId", });
    internal_static_waterRecycling_MonitorTankLevelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_waterRecycling_MonitorTankLevelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_MonitorTankLevelsResponse_descriptor,
        new java.lang.String[] { "TankId", "CurrentLevel", });
    internal_static_waterRecycling_RainwaterTankRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_waterRecycling_RainwaterTankRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_RainwaterTankRequest_descriptor,
        new java.lang.String[] { "TankId", });
    internal_static_waterRecycling_RainwaterTankResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_waterRecycling_RainwaterTankResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_RainwaterTankResponse_descriptor,
        new java.lang.String[] { "TankLevels", "CurrentTankUsed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
