// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWater.proto

package ds.hotWater;

public final class HotWaterImpl {
  private HotWaterImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotWater_SetTankTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotWater_SetTankTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotWater_SetTankTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotWater_SetTankTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotWater_SendUsageDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotWater_SendUsageDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotWater_SendUsageDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotWater_SendUsageDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016hotWater.proto\022\010hotWater\"0\n\031SetTankTem" +
      "peratureRequest\022\023\n\013desiredTemp\030\001 \001(\005\"2\n\032" +
      "SetTankTemperatureResponse\022\024\n\014confirmati" +
      "on\030\001 \001(\t\"h\n\024SendUsageDataRequest\022\024\n\014hotW" +
      "aterTemp\030\001 \001(\005\022\021\n\ttankLevel\030\002 \001(\005\022\020\n\010flo" +
      "wrate\030\003 \001(\005\022\025\n\rwaterPressure\030\004 \001(\005\"/\n\025Se" +
      "ndUsageDataResponse\022\026\n\016recommendation\030\001 " +
      "\001(\t2\303\001\n\010HotWater\022a\n\022SetTankTemperature\022#" +
      ".hotWater.SetTankTemperatureRequest\032$.ho" +
      "tWater.SetTankTemperatureResponse\"\000\022T\n\rS" +
      "endUsageData\022\036.hotWater.SendUsageDataReq" +
      "uest\032\037.hotWater.SendUsageDataResponse\"\000(" +
      "\001B\035\n\013ds.hotWaterB\014HotWaterImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hotWater_SetTankTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hotWater_SetTankTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotWater_SetTankTemperatureRequest_descriptor,
        new java.lang.String[] { "DesiredTemp", });
    internal_static_hotWater_SetTankTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hotWater_SetTankTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotWater_SetTankTemperatureResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_hotWater_SendUsageDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hotWater_SendUsageDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotWater_SendUsageDataRequest_descriptor,
        new java.lang.String[] { "HotWaterTemp", "TankLevel", "Flowrate", "WaterPressure", });
    internal_static_hotWater_SendUsageDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_hotWater_SendUsageDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotWater_SendUsageDataResponse_descriptor,
        new java.lang.String[] { "Recommendation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
