// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWater.proto

package ds.hotWater;

public interface SendUsageDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hotWater.SendUsageDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hotWaterTemp = 1;</code>
   */
  int getHotWaterTemp();

  /**
   * <code>int32 tankLevel = 2;</code>
   */
  int getTankLevel();

  /**
   * <code>int32 flowrate = 3;</code>
   */
  int getFlowrate();

  /**
   * <code>int32 waterPressure = 4;</code>
   */
  int getWaterPressure();
}
