// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWater.proto

package ds.hotWater;

public interface SendUsageDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hotWater.SendUsageDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recommendation = 1;</code>
   */
  java.lang.String getRecommendation();
  /**
   * <code>string recommendation = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecommendationBytes();
}
