// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWater.proto

package ds.hotWater;

/**
 * Protobuf type {@code hotWater.SendUsageDataRequest}
 */
public  final class SendUsageDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hotWater.SendUsageDataRequest)
    SendUsageDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SendUsageDataRequest.newBuilder() to construct.
  private SendUsageDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendUsageDataRequest() {
    hotWaterTemp_ = 0;
    tankLevel_ = 0;
    flowrate_ = 0;
    waterPressure_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SendUsageDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            hotWaterTemp_ = input.readInt32();
            break;
          }
          case 16: {

            tankLevel_ = input.readInt32();
            break;
          }
          case 24: {

            flowrate_ = input.readInt32();
            break;
          }
          case 32: {

            waterPressure_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.hotWater.HotWaterImpl.internal_static_hotWater_SendUsageDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.hotWater.HotWaterImpl.internal_static_hotWater_SendUsageDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.hotWater.SendUsageDataRequest.class, ds.hotWater.SendUsageDataRequest.Builder.class);
  }

  public static final int HOTWATERTEMP_FIELD_NUMBER = 1;
  private int hotWaterTemp_;
  /**
   * <code>int32 hotWaterTemp = 1;</code>
   */
  public int getHotWaterTemp() {
    return hotWaterTemp_;
  }

  public static final int TANKLEVEL_FIELD_NUMBER = 2;
  private int tankLevel_;
  /**
   * <code>int32 tankLevel = 2;</code>
   */
  public int getTankLevel() {
    return tankLevel_;
  }

  public static final int FLOWRATE_FIELD_NUMBER = 3;
  private int flowrate_;
  /**
   * <code>int32 flowrate = 3;</code>
   */
  public int getFlowrate() {
    return flowrate_;
  }

  public static final int WATERPRESSURE_FIELD_NUMBER = 4;
  private int waterPressure_;
  /**
   * <code>int32 waterPressure = 4;</code>
   */
  public int getWaterPressure() {
    return waterPressure_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (hotWaterTemp_ != 0) {
      output.writeInt32(1, hotWaterTemp_);
    }
    if (tankLevel_ != 0) {
      output.writeInt32(2, tankLevel_);
    }
    if (flowrate_ != 0) {
      output.writeInt32(3, flowrate_);
    }
    if (waterPressure_ != 0) {
      output.writeInt32(4, waterPressure_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (hotWaterTemp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, hotWaterTemp_);
    }
    if (tankLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, tankLevel_);
    }
    if (flowrate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, flowrate_);
    }
    if (waterPressure_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, waterPressure_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.hotWater.SendUsageDataRequest)) {
      return super.equals(obj);
    }
    ds.hotWater.SendUsageDataRequest other = (ds.hotWater.SendUsageDataRequest) obj;

    boolean result = true;
    result = result && (getHotWaterTemp()
        == other.getHotWaterTemp());
    result = result && (getTankLevel()
        == other.getTankLevel());
    result = result && (getFlowrate()
        == other.getFlowrate());
    result = result && (getWaterPressure()
        == other.getWaterPressure());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOTWATERTEMP_FIELD_NUMBER;
    hash = (53 * hash) + getHotWaterTemp();
    hash = (37 * hash) + TANKLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getTankLevel();
    hash = (37 * hash) + FLOWRATE_FIELD_NUMBER;
    hash = (53 * hash) + getFlowrate();
    hash = (37 * hash) + WATERPRESSURE_FIELD_NUMBER;
    hash = (53 * hash) + getWaterPressure();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.hotWater.SendUsageDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.hotWater.SendUsageDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.hotWater.SendUsageDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.hotWater.SendUsageDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.hotWater.SendUsageDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.hotWater.SendUsageDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.hotWater.SendUsageDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.hotWater.SendUsageDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.hotWater.SendUsageDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.hotWater.SendUsageDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.hotWater.SendUsageDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.hotWater.SendUsageDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.hotWater.SendUsageDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code hotWater.SendUsageDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hotWater.SendUsageDataRequest)
      ds.hotWater.SendUsageDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.hotWater.HotWaterImpl.internal_static_hotWater_SendUsageDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.hotWater.HotWaterImpl.internal_static_hotWater_SendUsageDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.hotWater.SendUsageDataRequest.class, ds.hotWater.SendUsageDataRequest.Builder.class);
    }

    // Construct using ds.hotWater.SendUsageDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hotWaterTemp_ = 0;

      tankLevel_ = 0;

      flowrate_ = 0;

      waterPressure_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.hotWater.HotWaterImpl.internal_static_hotWater_SendUsageDataRequest_descriptor;
    }

    @java.lang.Override
    public ds.hotWater.SendUsageDataRequest getDefaultInstanceForType() {
      return ds.hotWater.SendUsageDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.hotWater.SendUsageDataRequest build() {
      ds.hotWater.SendUsageDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.hotWater.SendUsageDataRequest buildPartial() {
      ds.hotWater.SendUsageDataRequest result = new ds.hotWater.SendUsageDataRequest(this);
      result.hotWaterTemp_ = hotWaterTemp_;
      result.tankLevel_ = tankLevel_;
      result.flowrate_ = flowrate_;
      result.waterPressure_ = waterPressure_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.hotWater.SendUsageDataRequest) {
        return mergeFrom((ds.hotWater.SendUsageDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.hotWater.SendUsageDataRequest other) {
      if (other == ds.hotWater.SendUsageDataRequest.getDefaultInstance()) return this;
      if (other.getHotWaterTemp() != 0) {
        setHotWaterTemp(other.getHotWaterTemp());
      }
      if (other.getTankLevel() != 0) {
        setTankLevel(other.getTankLevel());
      }
      if (other.getFlowrate() != 0) {
        setFlowrate(other.getFlowrate());
      }
      if (other.getWaterPressure() != 0) {
        setWaterPressure(other.getWaterPressure());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.hotWater.SendUsageDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.hotWater.SendUsageDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int hotWaterTemp_ ;
    /**
     * <code>int32 hotWaterTemp = 1;</code>
     */
    public int getHotWaterTemp() {
      return hotWaterTemp_;
    }
    /**
     * <code>int32 hotWaterTemp = 1;</code>
     */
    public Builder setHotWaterTemp(int value) {
      
      hotWaterTemp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 hotWaterTemp = 1;</code>
     */
    public Builder clearHotWaterTemp() {
      
      hotWaterTemp_ = 0;
      onChanged();
      return this;
    }

    private int tankLevel_ ;
    /**
     * <code>int32 tankLevel = 2;</code>
     */
    public int getTankLevel() {
      return tankLevel_;
    }
    /**
     * <code>int32 tankLevel = 2;</code>
     */
    public Builder setTankLevel(int value) {
      
      tankLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tankLevel = 2;</code>
     */
    public Builder clearTankLevel() {
      
      tankLevel_ = 0;
      onChanged();
      return this;
    }

    private int flowrate_ ;
    /**
     * <code>int32 flowrate = 3;</code>
     */
    public int getFlowrate() {
      return flowrate_;
    }
    /**
     * <code>int32 flowrate = 3;</code>
     */
    public Builder setFlowrate(int value) {
      
      flowrate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 flowrate = 3;</code>
     */
    public Builder clearFlowrate() {
      
      flowrate_ = 0;
      onChanged();
      return this;
    }

    private int waterPressure_ ;
    /**
     * <code>int32 waterPressure = 4;</code>
     */
    public int getWaterPressure() {
      return waterPressure_;
    }
    /**
     * <code>int32 waterPressure = 4;</code>
     */
    public Builder setWaterPressure(int value) {
      
      waterPressure_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 waterPressure = 4;</code>
     */
    public Builder clearWaterPressure() {
      
      waterPressure_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hotWater.SendUsageDataRequest)
  }

  // @@protoc_insertion_point(class_scope:hotWater.SendUsageDataRequest)
  private static final ds.hotWater.SendUsageDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.hotWater.SendUsageDataRequest();
  }

  public static ds.hotWater.SendUsageDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendUsageDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<SendUsageDataRequest>() {
    @java.lang.Override
    public SendUsageDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SendUsageDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SendUsageDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendUsageDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.hotWater.SendUsageDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

