// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWater.proto

package ds.hotWater;

public interface SetTankTemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hotWater.SetTankTemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
