// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWater.proto

package ds.hotWater;

public interface SetTankTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hotWater.SetTankTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 desiredTemp = 1;</code>
   */
  int getDesiredTemp();
}
